# Generated by Django 5.2.11 on 2026-02-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtime', '0002_room_privacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='empty_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
