# Generated by Django 5.1.6 on 2026-02-25 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_friendship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
